### ISSUE TITLE
Two questions about Metadata Displayer Example

### ISSUE THREAD

**Issue by jwdinkel** [googleworkspace/browser-samples#81]
Hello,

I need some assistance with this sample project.

First, can anybody explain the purpose of this line?

https://github.com/googleworkspace/browser-samples/blob/60774d9d6718dd0e3e8d8595e5b2b385cf27d377/drive/metadisplayer/metadisplayer.html#L41

Second, when implementing the client ID, I enter the Google Cloud Shell dev https address in the URL configuration, but it doesn't seem to work....

Accessing the Cloud Shell Web Preview shows this web page:
```
Metadata Displayer Example

{
  "error": "idpiframe_initialization_failed",
  "details": "Not a valid origin for the client: https://8080-cs-523946987037-default.cs-europe-west1-itbg.cloudshell.dev has not been registered for client ID 572678367491-6ltvbiv4j654fcid28h29jpgq4qk7kie.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and register this origin for your project's client ID."
}
```
![image](https://user-images.githubusercontent.com/7911734/120808783-b1ba6780-c549-11eb-82d9-e6dbdfba802b.png)

**Comment by sqrrrl** [comment]
This sample has been deleted/merged into the picker quickstart. But since the same questions apply:

App ID is the project # of the app. It's currently required by the Picker, though it's a bit redundant as the oauth token implies the same information. But for now, it's required.

As for the origin, you might have run into a caching issue with the origins. If you add an origin after the origin check it can take a while for it to start working (30m or so.) You can try clearing your browser cache in this case, or create a new client ID with the correct origin and use that instead. Unfortunately oauth requires a predictable/stable URL/origin which CloudShell doesn't really provide. You can find some discussion of the cache issue at https://stackoverflow.com/questions/42566296/google-api-authentication-not-valid-origin-for-the-client
